version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t codacy/teamcity-agent:$DOCKER_VERSION_PREFIX.$CIRCLE_BUILD_NUM --no-cache .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag codacy/teamcity-agent:$DOCKER_VERSION_PREFIX.$CIRCLE_BUILD_NUM codacy/teamcity-agent:latest
              docker push codacy/teamcity-agent:$DOCKER_VERSION_PREFIX.$CIRCLE_BUILD_NUM
              docker push codacy/teamcity-agent:latest
            fi